apiVersion: v1
kind: Service
metadata:
  name: chatml-relay
  labels:
    app: chatml-relay
spec:
  type: ClusterIP
  ports:
    - port: 8787
      targetPort: 8787
      protocol: TCP
      name: ws
  selector:
    app: chatml-relay
