/**
 * Authentication token management for backend API security.
 * Retrieves the token from Tauri via IPC and caches it for subsequent calls.
 *
 * The token is generated by Tauri when spawning the sidecar and passed via
 * environment variable. If the sidecar restarts, a new token is generated,
 * so we must invalidate the cache and re-fetch.
 */

let cachedToken: string | null = null;

/**
 * Get the authentication token for backend API calls.
 * In Tauri environment, retrieves the token via IPC command.
 * In non-Tauri environment (development), returns null.
 */
export async function getAuthToken(): Promise<string | null> {
  if (typeof window === 'undefined') return null;
  if (!(window as Window & { __TAURI__?: unknown }).__TAURI__) return null;

  if (cachedToken) return cachedToken;

  try {
    const { invoke } = await import('@tauri-apps/api/core');
    cachedToken = await invoke<string>('get_auth_token');
    return cachedToken;
  } catch (e) {
    console.error('Failed to get auth token:', e);
    return null;
  }
}

/**
 * Get the cached authentication token synchronously.
 * Returns null if the token hasn't been fetched yet.
 * Use this for WebSocket connections where async isn't practical.
 */
export function getCachedAuthToken(): string | null {
  return cachedToken;
}

/**
 * Initialize the auth token early during app startup.
 * Call this during app initialization to ensure the token is cached
 * before WebSocket connections are established.
 */
export async function initAuthToken(): Promise<void> {
  await getAuthToken();
}

/**
 * Clear the cached token. Call this when the sidecar restarts,
 * as a new token will be generated.
 */
export function clearAuthTokenCache(): void {
  cachedToken = null;
}
