package skills

import (
	"time"

	"github.com/chatml/chatml-backend/models"
)

// gstackDate is the date GStack skills were added to the catalog.
var gstackDate = time.Date(2026, 3, 27, 0, 0, 0, 0, time.UTC)

// gstackSkills defines the GStack skill catalog entries.
// Content is loaded from embedded .md files in init().
var gstackSkills = []models.Skill{
	// ── Planning & Strategy ──────────────────────────────────────────────
	{
		ID:          "gstack-office-hours",
		Name:        "Office Hours",
		Description: "YC Office Hours — two modes. Startup mode: six forcing questions that expose demand reality, status quo, desperate specificity, narrowest wedge, observation, and future-fit. Builder mode: design thinking brainstorm.",
		Category:    models.SkillCategoryPlanning,
		Author:      "GStack (Garry Tan)",
		Version:     "2.0.0",
		Preview:     "YC-style forcing questions before coding",
		SkillPath:   "gstack-office-hours.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-plan-ceo-review",
		Name:        "CEO Plan Review",
		Description: "CEO/founder-mode plan review. Rethink the problem, find the 10-star product, challenge premises, expand scope when it creates a better product. Four modes: SCOPE EXPANSION, SELECTIVE EXPANSION, HOLD SCOPE, SCOPE REDUCTION.",
		Category:    models.SkillCategoryPlanning,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Founder-mode plan review with scope challenge",
		SkillPath:   "gstack-plan-ceo-review.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-plan-eng-review",
		Name:        "Engineering Plan Review",
		Description: "Eng manager-mode plan review. Lock in the execution plan — architecture, data flow, diagrams, edge cases, test coverage, performance. Walks through issues interactively with opinionated recommendations.",
		Category:    models.SkillCategoryPlanning,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Architecture and execution plan review",
		SkillPath:   "gstack-plan-eng-review.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-plan-design-review",
		Name:        "Design Plan Review",
		Description: "Designer's eye plan review — rates each design dimension 0-10, explains what would make it a 10, then fixes the plan to get there. Works in plan mode.",
		Category:    models.SkillCategoryPlanning,
		Author:      "GStack (Garry Tan)",
		Version:     "2.0.0",
		Preview:     "Design dimension scoring with fix-to-10 loop",
		SkillPath:   "gstack-plan-design-review.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-design-consultation",
		Name:        "Design Consultation",
		Description: "Design consultation: understands your product, researches the landscape, proposes a complete design system (aesthetic, typography, color, layout, spacing, motion), and generates a font+color preview page.",
		Category:    models.SkillCategoryPlanning,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Full design system from research to preview",
		SkillPath:   "gstack-design-consultation.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-autoplan",
		Name:        "Auto Review Pipeline",
		Description: "Auto-review pipeline — reads the full CEO, design, and eng review skills from disk and runs them sequentially with auto-decisions using 6 decision principles.",
		Category:    models.SkillCategoryPlanning,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Orchestrated CEO → Design → Eng review pipeline",
		SkillPath:   "gstack-autoplan.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},

	// ── Development & Review ─────────────────────────────────────────────
	{
		ID:          "gstack-review",
		Name:        "Pre-Landing Review",
		Description: "Pre-landing PR review. Analyzes diff against the base branch for SQL safety, LLM trust boundary violations, conditional side effects, and other structural issues.",
		Category:    models.SkillCategoryDevelopment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Multi-pass PR analysis with adversarial review",
		SkillPath:   "gstack-review.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-investigate",
		Name:        "Investigate Bug",
		Description: "Systematic debugging with root cause investigation. Four phases: investigate, analyze, hypothesize, implement. Iron Law: no fixes without root cause.",
		Category:    models.SkillCategoryDevelopment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Root cause investigation before any fixes",
		SkillPath:   "gstack-investigate.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-design-review",
		Name:        "Design QA Review",
		Description: "Designer's eye QA: finds visual inconsistency, spacing issues, hierarchy problems, AI slop patterns, and slow interactions — then fixes them with atomic commits.",
		Category:    models.SkillCategoryDevelopment,
		Author:      "GStack (Garry Tan)",
		Version:     "2.0.0",
		Preview:     "Visual QA with AI slop detection and CSS fixes",
		SkillPath:   "gstack-design-review.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-codex",
		Name:        "Codex Review",
		Description: "OpenAI Codex CLI wrapper — three modes. Code review: independent diff review with pass/fail gate. Challenge: adversarial mode that tries to break your code. Consult: ask codex anything.",
		Category:    models.SkillCategoryDevelopment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Independent code review via OpenAI Codex",
		SkillPath:   "gstack-codex.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},

	// ── Security ─────────────────────────────────────────────────────────
	{
		ID:          "gstack-cso",
		Name:        "Security Audit (CSO)",
		Description: "Chief Security Officer mode. Infrastructure-first security audit: secrets archaeology, dependency supply chain, CI/CD pipeline security, LLM/AI security, OWASP Top 10, and STRIDE threat modeling.",
		Category:    models.SkillCategorySecurity,
		Author:      "GStack (Garry Tan)",
		Version:     "2.0.0",
		Preview:     "Full security audit with OWASP and STRIDE",
		SkillPath:   "gstack-cso.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-careful",
		Name:        "Careful Mode",
		Description: "Safety guardrails for destructive commands. Warns before rm -rf, DROP TABLE, force-push, git reset --hard, kubectl delete, and similar destructive operations.",
		Category:    models.SkillCategorySecurity,
		Author:      "GStack (Garry Tan)",
		Version:     "0.1.0",
		Preview:     "Warns before destructive shell commands",
		SkillPath:   "gstack-careful.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-freeze",
		Name:        "Freeze Edits",
		Description: "Restrict file edits to a specific directory for the session. Blocks Edit and Write outside the allowed path.",
		Category:    models.SkillCategorySecurity,
		Author:      "GStack (Garry Tan)",
		Version:     "0.1.0",
		Preview:     "Directory-scoped edit restrictions",
		SkillPath:   "gstack-freeze.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-guard",
		Name:        "Guard Mode",
		Description: "Full safety mode: destructive command warnings + directory-scoped edits. Combines /careful (warns before rm -rf, DROP TABLE, force-push) with /freeze (blocks edits outside a specified directory).",
		Category:    models.SkillCategorySecurity,
		Author:      "GStack (Garry Tan)",
		Version:     "0.1.0",
		Preview:     "Combined careful + freeze safety mode",
		SkillPath:   "gstack-guard.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-unfreeze",
		Name:        "Unfreeze Edits",
		Description: "Clear the freeze boundary set by /freeze, allowing edits to all directories again.",
		Category:    models.SkillCategorySecurity,
		Author:      "GStack (Garry Tan)",
		Version:     "0.1.0",
		Preview:     "Remove directory edit restrictions",
		SkillPath:   "gstack-unfreeze.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},

	// ── Quality ──────────────────────────────────────────────────────────
	{
		ID:          "gstack-qa",
		Name:        "QA Testing",
		Description: "Systematically QA test a web application and fix bugs found. Runs QA testing, then iteratively fixes bugs in source code, committing each fix atomically and re-verifying.",
		Category:    models.SkillCategoryQuality,
		Author:      "GStack (Garry Tan)",
		Version:     "2.0.0",
		Preview:     "Full QA cycle: test, fix, verify, commit",
		SkillPath:   "gstack-qa.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-qa-only",
		Name:        "QA Report Only",
		Description: "Report-only QA testing. Systematically tests a web application and produces a structured report with health score, screenshots, and repro steps — but never fixes anything.",
		Category:    models.SkillCategoryQuality,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "QA testing without fixes — report only",
		SkillPath:   "gstack-qa-only.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-benchmark",
		Name:        "Performance Benchmark",
		Description: "Performance regression detection using the browse daemon. Establishes baselines for page load times, Core Web Vitals, and resource sizes. Compares before/after on every PR.",
		Category:    models.SkillCategoryQuality,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Page load and Core Web Vitals benchmarking",
		SkillPath:   "gstack-benchmark.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},

	// ── Deployment ───────────────────────────────────────────────────────
	{
		ID:          "gstack-ship",
		Name:        "Ship",
		Description: "Ship workflow: detect + merge base branch, run tests, review diff, bump VERSION, update CHANGELOG, commit, push, create PR.",
		Category:    models.SkillCategoryDeployment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Automated CI/CD pipeline to PR creation",
		SkillPath:   "gstack-ship.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-land-and-deploy",
		Name:        "Land & Deploy",
		Description: "Land and deploy workflow. Merges the PR, waits for CI and deploy, verifies production health via canary checks.",
		Category:    models.SkillCategoryDeployment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Merge PR, monitor deploy, verify production",
		SkillPath:   "gstack-land-and-deploy.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-document-release",
		Name:        "Document Release",
		Description: "Post-ship documentation update. Reads all project docs, cross-references the diff, updates README/ARCHITECTURE/CONTRIBUTING/CLAUDE.md to match what shipped.",
		Category:    models.SkillCategoryDeployment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Auto-update docs after shipping changes",
		SkillPath:   "gstack-document-release.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-canary",
		Name:        "Canary Monitoring",
		Description: "Post-deploy canary monitoring. Watches the live app for console errors, performance regressions, and page failures using the browse daemon.",
		Category:    models.SkillCategoryDeployment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Continuous post-deploy health monitoring",
		SkillPath:   "gstack-canary.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
	{
		ID:          "gstack-setup-deploy",
		Name:        "Setup Deploy",
		Description: "Configure deployment settings for /land-and-deploy. Detects your deploy platform (Fly.io, Render, Vercel, Netlify, Heroku, GitHub Actions, custom) and writes config to CLAUDE.md.",
		Category:    models.SkillCategoryDeployment,
		Author:      "GStack (Garry Tan)",
		Version:     "1.0.0",
		Preview:     "Auto-detect and configure deployment platform",
		SkillPath:   "gstack-setup-deploy.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},

	// ── Documentation ────────────────────────────────────────────────────
	{
		ID:          "gstack-retro",
		Name:        "Engineering Retrospective",
		Description: "Weekly engineering retrospective. Analyzes commit history, work patterns, and code quality metrics with persistent history and trend tracking.",
		Category:    models.SkillCategoryDocumentation,
		Author:      "GStack (Garry Tan)",
		Version:     "2.0.0",
		Preview:     "Git-based team retro with trend tracking",
		SkillPath:   "gstack-retro.md",
		CreatedAt:   gstackDate,
		UpdatedAt:   gstackDate,
	},
}

func init() {
	// Load embedded content into GStack skills and append to BuiltInSkills.
	for i := range gstackSkills {
		// Derive the .md filename from the skill ID (strip "gstack-" prefix)
		name := gstackSkills[i].ID[len("gstack-"):]
		gstackSkills[i].Content = gstackSkillContent(name)
	}
	BuiltInSkills = append(BuiltInSkills, gstackSkills...)
}
